export const videos = [
    {
      "title": "Ep.1 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Introduction - 00:24 to 06:48\nMindfulness Pausing for Presence - 06:49 to 14:00\nReflection - 14:01 to 15:10\nQuestions and Comments - 15:11\n\n------------------------------\n\nHow can you engineer your environment to best practice mindfulness if you don't have much control over it?\nAnswer 15:35\n\nHow often should I be practicing mindfulness?\nAnswer 17:19\n\nHow can you practice mindfulness while doing something else at the same time?\nAnswer 19:02\n\nIf I feel sleepy, should I allow myself to fall asleep?\nAnswer 20:14\n\nWhat physical positioning do you recommend for practicing mindfulness?\nAnswer 21:43\n\n----------------------------------\n\nGuided meditation led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness.  Thank you to Mary-Jo, and to everyone who joined us!  If you missed us, no worries ... we'll be hosting online streams that include guided meditations every Wednesday for a while at noon PST and 3 pm EST.  \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U.  If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca.\n\nHere is a poster outlining our study\nhttps://drive.google.com/file/d/1y2k4ProoU-waQv_B2JgHcIW_bEeuLGDF/view\n\nHere is a leaflet describing our study\nhttps://drive.google.com/file/d/138MUCSDNfgny3iQywUZ0dJqJSJQm1EYc/view\n\nWe hope to see you again next week!",
      "videoLength": "1390",
      "thumbnailUrl": "https://i.ytimg.com/vi/fqsGwk11qZE/maxresdefault.jpg",
      "videoId": "fqsGwk11qZE",
      "videoUrl": "https://www.youtube.com/watch?v=fqsGwk11qZE",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 55,
      "likeCount": 3,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-06",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=fqsGwk11qZE",
      "timestamp": "2023-03-22T07:46:32.952Z"
    },
    {
      "title": "Ep.2 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Introduction - 00:24 to 08:27\nMindfulness for Resilience - 08:27 to 19:20\nQuestions and Comments - 19:38\n\n---------------------------\n\nCan you explain the difference between mindfulness and meditation? \nAnswer at 21:17\n\nDo you have a strategy to create an environmental that is conducive to mindfulness? And particularly if you have a situation where it is hard to control your environment?\nAnswer 23:41\n\nHow do you suggest overcoming barriers to mindfulness practice that is specific to SCI? How to access techniques with barriers to our body\nAnswer 26:59\n\nIs there an age limitation to mindfulness, and when I practice, should I allow myself to sleep if needed or should I force myself to stay awake?\nAnswer 31:58\n\nThe pain in back was different, and I was more aware of it after mindfulness session. Does that sound right?\nAnswer 35:42\n\nIs there a difference between meditating with eyes closed vs eyes open? \nAnswer 38:36\n\nHow often would you recommend practicing mindfulness?\nAnswer 40:55\n\nShould I be a skeptic of mindfulness and meditation?\nAnswer 43:37\n\nAre there things we can do during the week to prepare for a mindfulness session next week?\nAnswer 46:10\n\n--------------------------------\n\nGuided meditation led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness.  Thank you to Mary-Jo, and to everyone who joined us!  If you missed us, no worries ... we'll be hosting online streams that include guided meditations every Wednesday for a while at noon PST and 3 pm EST.  \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U.  If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca.\n\nHere is a poster outlining our study\nhttps://drive.google.com/file/d/1y2k4ProoU-waQv_B2JgHcIW_bEeuLGDF/view\n\nHere is a leaflet describing our study\nhttps://drive.google.com/file/d/138MUCSDNfgny3iQywUZ0dJqJSJQm1EYc/view\n\nWe hope to see you again next week!",
      "videoLength": "2928",
      "thumbnailUrl": "https://i.ytimg.com/vi/bIirETEJ--o/maxresdefault.jpg",
      "videoId": "bIirETEJ--o",
      "videoUrl": "https://www.youtube.com/watch?v=bIirETEJ--o",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 36,
      "likeCount": 1,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-06",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=bIirETEJ--o",
      "timestamp": "2023-03-22T07:46:34.796Z"
    },
    {
      "title": "Ep.3 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Sonya and Delynne Program Introduction 00:24 to 03:08 \nMary-Jo Introduction 03:09 to 08:57  \nMindfulness for Resilience 08:58 to 18:05 \nQuestions 18:11 to 26:58 \nClosing Remarks 26:59 to 28:12 \n\n---------------------------------\n\nIf you find you're itchy or uncomfortable in the middle of being mindful, what do you do? \nAnswer at 18:54\n\nFollowing up on \"homework\" from previous week\nBegins at 20:20\n\nWhen experiencing symptoms of autonomic dysreflexia (such as chills), what can help me stay calm and grounded?\nAnswer at 22:37\n\nCan you explain the doubling the exhaling?\nAnswer at 26:30\n\n---------------------------------\n\nGuided meditation led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness.  Thank you to Mary-Jo, and to everyone who joined us!  If you missed us, no worries ... we'll be hosting online streams that include guided meditations every Wednesday for a while at noon PST and 3 pm EST.  \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U.  If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca.\n\nHere is a poster outlining our study\nhttps://drive.google.com/file/d/1y2k4ProoU-waQv_B2JgHcIW_bEeuLGDF/view\n\nHere is a leaflet describing our study\nhttps://drive.google.com/file/d/138MUCSDNfgny3iQywUZ0dJqJSJQm1EYc/view\n\nWe hope to see you again next week!",
      "videoLength": "1699",
      "thumbnailUrl": "https://i.ytimg.com/vi/FOaUiXzMlCc/maxresdefault.jpg",
      "videoId": "FOaUiXzMlCc",
      "videoUrl": "https://www.youtube.com/watch?v=FOaUiXzMlCc",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 24,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-12",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=FOaUiXzMlCcc",
      "timestamp": "2023-03-22T07:46:35.974Z"
    },
    {
      "title": "Ep.4 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Introduction 00:24 to 06:27\nMindfulness for Resilience 06:28 to 18:56\nQuestions and comments 19:00\n\n--------------------------------------\n\nIs there a difference between doing mindfulness in a group or on your own?\nAnswer at 19:20\n\nReflection of last weeks \"homework\"\nBegins at 20:45\n\nIn our home environment, what should we focus on?\nAnswer at 23:42\n\nWhen you say \"feel a certain area of your body\", what should someone who doesn't have sensation in that area do?\nAnswer 25:53\n\nSome deep breaths are deeper than others, how can you handle those a little easier?\nAnswer 28:13\n\nWhat is beneficial about tuning into your pain?\nAnswer 32:44\n\nClosing Remarks\nBegins at 36:55\n\n--------------------------------------\n\nGuided meditation led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness.  Thank you to Mary-Jo, and to everyone who joined us!  If you missed us, no worries ... we'll be hosting online streams that include guided meditations every Wednesday for a while at noon PST and 3 pm EST.  \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U.  If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca.\n\nHere is a poster outlining our study\nhttps://drive.google.com/file/d/1y2k4...\n\nHere is a leaflet describing our study\nhttps://drive.google.com/file/d/138MU...\n\nWe hope to see you again next week!",
      "videoLength": "2299",
      "thumbnailUrl": "https://i.ytimg.com/vi/EAcP-uRUsnM/maxresdefault.jpg",
      "videoId": "EAcP-uRUsnM",
      "videoUrl": "https://www.youtube.com/watch?v=EAcP-uRUsnM",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 22,
      "likeCount": 1,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-14",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=EAcP-uRUsnMM",
      "timestamp": "2023-03-22T07:46:37.067Z"
    },
    {
      "title": "Ep.5 - Arriving In Presence, Pausing to Become Present",
      "description": "Paul introduces Mary-Jo 00:24 to 01:14\nOpening remarks 01:14 to 01:50\nMindfulness for Resilience 01:51 to 11:21\n\n-------------------------------------\n\n~ Feeling and noticing the Sensory body\n~ Observing movement of breath\n~ Using the exhale to feel the Weight of the body\n~ Noticing all Sensations feelings, thoughts\n~ Observing Movement of thought live waves on the surface of the ocean\n~ Stability of self like depth of ocean\n~ Moving thoughts sensations\n~ The contrast of being holding opposites together\n\n-------------------------------------\n\nOverview of how these sessions may evolve over time on this channel. If you're interrupted during a session, how can you overcome that?\nAnswer at 13:18\nCircles back to answer \"interrupted\" question at 17:45\n\nHands over the eyes really helped with falling into mindfulness \nReflection at 16:57\n\nWhat is the impact of mindfulness on the brain? \nAnswer at 19:15\n\nNeural plasticity?\nAnswer at 23:21\n\n--------------------------------------\n\nResources:\nhttps://www.tarabrach.com/\nhttps://jackkornfield.com/ \nhttps://www.nicabm.com/faculty/peter-levine/\n\n---------------------------------------\n\nGuided meditation led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness.  Thank you to Mary-Jo, and to everyone who joined us!  If you missed us, no worries ... we'll be hosting online streams that include guided meditations every Wednesday for a while at noon PST and 3 pm EST.  \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U.  If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca.\n\nHere is a poster outlining our study\nhttps://drive.google.com/file/d/1y2k4...\n\nHere is a leaflet describing our study\nhttps://drive.google.com/file/d/138MU...\n\nWe hope to see you again next week!",
      "videoLength": "1554",
      "thumbnailUrl": "https://i.ytimg.com/vi/RxtQKK3PwYk/maxresdefault.jpg",
      "videoId": "RxtQKK3PwYk",
      "videoUrl": "https://www.youtube.com/watch?v=RxtQKK3PwYk",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 13,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-15",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=RxtQKK3PwYkk",
      "timestamp": "2023-03-22T07:46:38.520Z"
    },
    {
      "title": "Ep.6 - Adopting an Attitude of Friendliness",
      "description": "Mary-Jo Reflection 00:24 to 05:08\nMindfulness for Resilience 05:09 to 15:28\nQuestions 16:27 to 19:15\n\n---------------------------------------\n\n~ Pausing\n~ Relaxing and becoming present\n~ Awakening to your senses\n~ Am I doing it right?\n~ Our habitual self judgement and perfectionism.\n~ Meeting a new friend creates the patience\n~ Mindfulness is not another demand\n~ Friendliness, kindness and compassion\n~ Like training a new puppy\n~ The mechanism of a smile at the eyes and within the whole being.\n~ Using the smile to allow acceptance & compassion of all states are being as they are in the moment\n\n---------------------------------------\n\nEmpathy and the parts of our brain that are developed through mindfulness?\nAnswer at 16:45\n\n----------------------------------------\n\nResources:\nhttps://www.curablehealth.com/blog/brain-infographic\n\n-----------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1326",
      "thumbnailUrl": "https://i.ytimg.com/vi/IA_y_YxhSZE/maxresdefault.jpg",
      "videoId": "IA_y_YxhSZE",
      "videoUrl": "https://www.youtube.com/watch?v=IA_y_YxhSZE",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 16,
      "likeCount": 1,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-15",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=IA_y_YxhSZEE",
      "timestamp": "2023-03-22T07:46:39.638Z"
    },
    {
      "title": "SCI&U Study | Informational Video",
      "description": "Join us on YouTube or Facebook for a LIVE guided meditation every Wednesday (except for Canada Day!) at 3 pm EST or noon PST.\n\n- Visit www.sci-and-u.ca for more information about our related coaching study\n- Follow us on Instagram www.instagram.com/sciandustudy\n- Follow us on Facebook www.facebook.com/SCIandU1\n- Follow us on Twitter www.twitter.com/SCIandU1",
      "videoLength": "139",
      "thumbnailUrl": "https://i.ytimg.com/vi/NySa0ldaIUQ/maxresdefault.jpg",
      "videoId": "NySa0ldaIUQ",
      "videoUrl": "https://www.youtube.com/watch?v=NySa0ldaIUQ",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 51,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-15",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=NySa0ldaIUQQ",
      "timestamp": "2023-03-22T07:46:40.907Z"
    },
    {
      "title": "Ep.7 - Conscious Relaxing",
      "description": "Teri introduction 00:24 to 01:25\nOpening remarks 1:26 to 05:41\nMindfulness for Resilience 05:42 to 16:31\nReflection 16:32 to 18:30\n\n--------------------------------------\n\n~ Using the breathtaking become aware of tension\n~ Using awareness to release the persistent demands of stress & life which can cause chronic muscle tension and anxiety\n~ Building tolerance and endurance by dissolving tension and the stress hormones, using the tool of mindfulness for health to build resiliency\n~ Finding Ground, stabilization\n~ Conscious relaxing\n~ Adopting attitude of friendliness and non duality\n~ Attention without tension\n\n--------------------------------------\n\nComments on the importance of being outside, present, with nature \n18:31 \n\nComments on how mindfulness has helped calm leg spasms \n20:25\n\nAnything that you can suggest for lack of breath, or feeling light headed while attempting deep/regulated breathing? \nAnswer at 21:35\n\n\nTeri talking about finding time and being present in different situations throughout the day\n22:45 (Mary-Jo responds at 24:36)\n\n--------------------------------------\n\nResources:\nhttp://www.normandoidge.com/ \nhttp://www.mindfulnessinstitute.ca/neuroscience-labs\n\n---------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1611",
      "thumbnailUrl": "https://i.ytimg.com/vi/dofp4VJe0tw/maxresdefault.jpg",
      "videoId": "dofp4VJe0tw",
      "videoUrl": "https://www.youtube.com/watch?v=dofp4VJe0tw",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 10,
      "likeCount": 2,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-22",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=dofp4VJe0tww",
      "timestamp": "2023-03-22T07:46:42.027Z"
    },
    {
      "title": "Ep.8 - Tuning into Your Senses",
      "description": "Introduction 00:24 to 06:09\nMindfulness for Resilience 06:10 to 14:40\nReflection on our 6 Senses - 14:41 to 16:30\nQuestions 16:31 to 31:15\n\n---------------------------------------\n\n~ A stale state of mind exists when we are in judgement of self.\n~ We loose choice when we are disembodied from our ‘felt-sense’, we become ‘rigid’\n~ Bringing kind attention to all of your senses: sight, smells, taste, sounds, touch\n~ Acceptance and Curiosity allow for spaciousness and fluidity.\n~ Coming back to the Sensory body with kind attention, no judgements\n~ Filtering through the 5 senses and noticing the different sensations for each.\n\n----------------------------------------\n\nSadness feeling during mindfulness, is that normal?\nAnswer at 17:20\n\nCan you explain awareness of breathing?\nAnswer at 21:00\n\nIs there a way to talk yourself into a good sleep using mindfulness? \nAnswer at 25:53\nYoga Nidra Information - https://en.m.wikipedia.org/wiki/Yoga_nidra\n\nDo you have suggestions how I could benefit from the outdoors more? To not lose focus and to appreciate my surroundings \nAnswer at 29:40\n\n----------------------------------\n\nResources:\nhttps://paincareu.com/\n\n----------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1948",
      "thumbnailUrl": "https://i.ytimg.com/vi/rgMv-lQvSe8/maxresdefault.jpg",
      "videoId": "rgMv-lQvSe8",
      "videoUrl": "https://www.youtube.com/watch?v=rgMv-lQvSe8",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 10,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-05-28",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=rgMv-lQvSe88",
      "timestamp": "2023-03-22T07:46:43.223Z"
    },
    {
      "title": "Ep.9 - Working with the Breath-Movement and Sensations",
      "description": "Introduction 00:24 to 03:19\nMindfulness for Resilience 03:20 to 12:36\nReflection 12:37 to 14:16\nQuestions 14:17 \n\n-----------------------------------------\n\n~ What does the breath feel like?\n~ Notice the inhale expansion\n~ Notice the exhale releasing, deepening\n~ Fill the chest, notice what you feel.\n\n-----------------------------------------\n\nEnergy and the sixth sense? \nAnswer at 16:07\n\nControlling chronic pain with energy\nAnswer at 21:00\nAnne shares her pain story at 24:32\n\nWhy do I sweat when practicing mindfulness, but not anytime else?\nAnswer at 30:11\n\n----------------------------------------\n\nResources:\nhttps://www.psychologytoday.com/ca/blog/psychiatry-the-people/201901/how-yoga-and-breathing-help-the-brain-unwind\nhttp://skepdic.com/vibrationalmedicine.html\n\n-----------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "2052",
      "thumbnailUrl": "https://i.ytimg.com/vi/L855tsxc7vY/maxresdefault.jpg",
      "videoId": "L855tsxc7vY",
      "videoUrl": "https://www.youtube.com/watch?v=L855tsxc7vY",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 13,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-06-05",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=L855tsxc7vYY",
      "timestamp": "2023-03-22T07:46:44.317Z"
    },
    {
      "title": "Ep.10 - It’s all About an Attitude of Friendliness. Kind Attention",
      "description": "Introduction 00:24 to 11:12\nMindfulness for Resilience 11:13 to 19:45\nReflection 19:46\n\n-------------------------------------\n\n~ Change and Nature\n~ The changing world, environment\n~ The unchanging soul essence\n~ Changes of pandemic\n~ What is our constant?\n~ The capacity to hold all that is\n~ Pausing\n~ Conscious relaxing\n~ Sensory body\n~ Conscious breathing\n~ Perfectionism\n~ Using the smile throughout the body and bringing tenderness to heart while noticing the changing flow of sensations.\n\n-------------------------------------\n\nResources:\nhttp://www.normandoidge.com/?page_id=1042\nhttps://www.theatlantic.com/health/archive/2015/07/mindfulness-meditation-empathy-compassion/398867/\nhttps://greatergood.berkeley.edu/article/item/does_mindfulness_make_you_compassionate\n\n--------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1343",
      "thumbnailUrl": "https://i.ytimg.com/vi/etfNdMhdocs/maxresdefault.jpg",
      "videoId": "etfNdMhdocs",
      "videoUrl": "https://www.youtube.com/watch?v=etfNdMhdocs",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 20,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-06-11",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=etfNdMhdocss",
      "timestamp": "2023-03-22T07:46:45.777Z"
    },
    {
      "title": "Ep.11 - Breath as a Constant Stabilizer",
      "description": "Introduction 00:24 to 05:38\nMindfulness for Resilience 05:39 to 14:14\nReflection 14:15 to 16:40\nQuestions 16:41\n\n-----------------------------------\n\n~ Smooth rhythmic breathing slows down NS\n~ Available anytime\n~ Sensations of the breath\n~ Steadying the Mind calming the body\n~ My body has weight and my body breathes I am Stable and at Ease.\n~ One Breath Awareness throughout the day\n~ Longer sittings\n\n-----------------------------------\n\nWill the mindfulness sessions get longer as we move forward each week?\nAnswer at 16:49\n\n------------------------------------\n\nResources:\nhttps://www.scientificamerican.com/article/proper-breathing-brings-better-health/\nhttps://www.ncbi.nlm.nih.gov/pmc/articles/PMC6137615/\n\n-------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1112",
      "thumbnailUrl": "https://i.ytimg.com/vi/L0H32zEvKok/maxresdefault.jpg",
      "videoId": "L0H32zEvKok",
      "videoUrl": "https://www.youtube.com/watch?v=L0H32zEvKok",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 27,
      "likeCount": 1,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-06-18",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=L0H32zEvKok",
      "timestamp": "2023-03-22T07:46:46.989Z"
    },
    {
      "title": "E.12 - Counting the Breath",
      "description": "Introduction 00:24 to 09:50\nMindfulness for Resilience 09:51 to 21:47\nReflection 21:48 to 24:14\nQuestions 24:15\n\n--------------------------------------\n\n~ Why Practice?\n~ Review of the Basics\n~ Steadying the breath with Calm and Ease\n~ Where do you feel the breath\n~ Counting the breath at the end of the Exhale 1 up to 5\n~ Exhale is a relax\n~ Counting 5% / Awareness 95%\n\n---------------------------------------\n\nIs there a difference in counting frontwards or backwards?\nAnswer at 24:32\n\nIs there a certain length to practice mindfulness for beginners? \nAnswer at 26:46\n\n---------------------------------------\n\nResources: \nhttps://yogainternational.com/article/view/soothe-your-nervous-system-with-2-to-1-breathing/\n\n----------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1749",
      "thumbnailUrl": "https://i.ytimg.com/vi/crFgWXHhYVQ/maxresdefault.jpg",
      "videoId": "crFgWXHhYVQ",
      "videoUrl": "https://www.youtube.com/watch?v=crFgWXHhYVQ",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 11,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-06-25",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=crFgWXHhYVQQ",
      "timestamp": "2023-03-22T07:46:48.254Z"
    },
    {
      "title": "Quick Session - Mindfulness for Resilience w/ Mary-Jo Fetterly",
      "description": "This is a quick 8 minute \"Mindfulness for Resilience\" session to allow you to practise mindfulness between the live weekly videos. Mindfulness becomes easier to practise the more you practise! \n\n-------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "523",
      "thumbnailUrl": "https://i.ytimg.com/vi/ZTJhzjF480s/maxresdefault.jpg",
      "videoId": "ZTJhzjF480s",
      "videoUrl": "https://www.youtube.com/watch?v=ZTJhzjF480s",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 237,
      "likeCount": 7,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-07-07",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=ZTJhzjF480ss",
      "timestamp": "2023-03-22T07:46:49.671Z"
    },
    {
      "title": "Ep.13 - Revisiting Counting the Breath, For a Longer Time",
      "description": "00:24 to 07:57 Introduction\n07:58 to 22:56 Mindfulness for Resilience\n22:57 to 28:00 Reflection\n\n----------------------------------\n\n~ Using the Spine to come back to present time awareness\n~ Going with the flow\n~ Using The spine and the wave of the spine to bring us back into the present moment.\n~ Using the spine to connect the head and the body with the breath.\n~ Counting to ten, then twenty, longer practice.\n~ Inhale-Exhale-Relax-Repeat\n~ Returning to the breath and starting over\n\n-----------------------------------\n\nResources:\nhttps://positivepsychology.com/mindfulness-brain-research-neuroscience/\n\n------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1686",
      "thumbnailUrl": "https://i.ytimg.com/vi/IchlJHVvTG8/maxresdefault.jpg",
      "videoId": "IchlJHVvTG8",
      "videoUrl": "https://www.youtube.com/watch?v=IchlJHVvTG8",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 13,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-07-09",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=IchlJHVvTG8",
      "timestamp": "2023-03-22T07:46:50.886Z"
    },
    {
      "title": "Ep.14 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "00:24 to 10:16 Introduction \n10:17 to 25:53 Mindfulness for Resilience \n25:54 to 28:36 Reflection\n28:37 Questions\n\n------------------------------------\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "2157",
      "thumbnailUrl": "https://i.ytimg.com/vi/wL-SJWWZi08/maxresdefault.jpg",
      "videoId": "wL-SJWWZi08",
      "videoUrl": "https://www.youtube.com/watch?v=wL-SJWWZi08",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 4,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-07-30",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=wL-SJWWZi08",
      "timestamp": "2023-03-22T07:46:52.141Z"
    },
    {
      "title": "Ep. 15 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Mindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1878",
      "thumbnailUrl": "https://i.ytimg.com/vi/5auJAc_POjk/maxresdefault.jpg",
      "videoId": "5auJAc_POjk",
      "videoUrl": "https://www.youtube.com/watch?v=5auJAc_POjk",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 4,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-08-06",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=5auJAc_POjkk",
      "timestamp": "2023-03-22T07:46:53.269Z"
    },
    {
      "title": "Ep.16 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Mindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "2442",
      "thumbnailUrl": "https://i.ytimg.com/vi/UE-2fcRF50I/maxresdefault.jpg",
      "videoId": "UE-2fcRF50I",
      "videoUrl": "https://www.youtube.com/watch?v=UE-2fcRF50I",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 5,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-08-17",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=UE-2fcRF50II",
      "timestamp": "2023-03-22T07:46:54.405Z"
    },
    {
      "title": "Ep.17 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Mindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1339",
      "thumbnailUrl": "https://i.ytimg.com/vi/PXeLBGsN7RQ/maxresdefault.jpg",
      "videoId": "PXeLBGsN7RQ",
      "videoUrl": "https://www.youtube.com/watch?v=PXeLBGsN7RQ",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 2,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-08-27",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=PXeLBGsN7RQ",
      "timestamp": "2023-03-22T07:46:55.576Z"
    },
    {
      "title": "Ep. 18 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Mindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1410",
      "thumbnailUrl": "https://i.ytimg.com/vi/gSHrhkUDaJs/maxresdefault.jpg",
      "videoId": "gSHrhkUDaJs",
      "videoUrl": "https://www.youtube.com/watch?v=gSHrhkUDaJs",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 2,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-09-07",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=gSHrhkUDaJss",
      "timestamp": "2023-03-22T07:46:57.113Z"
    },
    {
      "title": "Ep.19 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Mindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1886",
      "thumbnailUrl": "https://i.ytimg.com/vi/gFraR_xY21U/maxresdefault.jpg",
      "videoId": "gFraR_xY21U",
      "videoUrl": "https://www.youtube.com/watch?v=gFraR_xY21U",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 10,
      "likeCount": 1,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-09-10",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=gFraR_xY21UU",
      "timestamp": "2023-03-22T07:46:58.138Z"
    },
    {
      "title": "Ep. 20 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "\"The lover of nature is he whose inward and outward senses are still truly adjusted to each other; who has retained the spirit of infancy even into the era of manhood.\" - Ralph Waldo Emerson, Nature\n\nMindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1980",
      "thumbnailUrl": "https://i.ytimg.com/vi/HulBWVb5_CE/maxresdefault.jpg",
      "videoId": "HulBWVb5_CE",
      "videoUrl": "https://www.youtube.com/watch?v=HulBWVb5_CE",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 3,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-09-25",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=HulBWVb5_CEE",
      "timestamp": "2023-03-22T07:46:59.191Z"
    },
    {
      "title": "Ep. 21 - Mindfulness for Resilience w/ Mary-Jo",
      "description": "Mindfulness Training Sessions led by Mary-Jo Fetterly, a Vancouver native and pioneer in the field of adaptive yoga and mindfulness. \n\nThis series has been sponsored by the Craig Neilsen Foundation and is an extension of a peer led health coaching program for people with SCI called SCI&U. If you are interested in learning more about this series or the program, you can contact us at sciandustudy@utoronto.ca. For more information about Mary-Jo, visit her website at https://mary-jo.com/.",
      "videoLength": "1451",
      "thumbnailUrl": "https://i.ytimg.com/vi/rgvQqyxgU8M/maxresdefault.jpg",
      "videoId": "rgvQqyxgU8M",
      "videoUrl": "https://www.youtube.com/watch?v=rgvQqyxgU8M",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 17,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "People & Blogs",
      "publishDate": "2020-10-01",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=rgvQqyxgU8M",
      "timestamp": "2023-03-22T07:47:00.456Z"
    },
    {
      "title": "Mindfulness with Mary-Jo Dated October 21, 2020",
      "description": "",
      "videoLength": "1767",
      "thumbnailUrl": "https://i.ytimg.com/vi/AkgcLvwIsqw/maxresdefault.jpg",
      "videoId": "AkgcLvwIsqw",
      "videoUrl": "https://www.youtube.com/watch?v=AkgcLvwIsqw",
      "channelId": "UCmrIralvsXc96VSPzzXmUNg",
      "channelUrl": "https://www.youtube.com/channel/UCmrIralvsXc96VSPzzXmUNg",
      "keywords": "",
      "author": "SCI&U Study",
      "profileUrl": "http://www.youtube.com/@sciustudy6173",
      "viewCount": 6,
      "likeCount": null,
      "authorThumbnailUrl": "https://yt3.ggpht.com/ytc/AL5GRJVv303FUn6M9QbU6tNFoTM8lBsH--tVQu6VWiUX=s176-c-k-c0x00ffffff-no-rj",
      "subscriberCount": "79 subscribers",
      "category": "Entertainment",
      "publishDate": "2020-11-03",
      "isLiveContent": false,
      "isFamilySafe": true,
      "query": "https://www.youtube.com/watch?v=AkgcLvwIsqw",
      "timestamp": "2023-03-22T07:47:01.678Z"
    }
  ]